DROP SEQUENCE USER_INFO_SEQ;
DROP TABLE USER_INFO;
CREATE SEQUENCE USER_INFO_SEQ;

CREATE TABLE USER_INFO(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(500) NOT NULL,
	USER_PW VARCHAR2(1000) NOT NULL,
	USER_ROLE VARCHAR2(100) NOT NULL,
	USER_NICKNAME VARCHAR2(500) NOT NULL,
	USER_REGDATE DATE NOT NULL,
	SNS_TYPE VARCHAR2(20),
	SNS_ID VARCHAR2(500),
	USER_ACTIVE VARCHAR2(20) NOT NULL,
	CONSTRAINTS USER_ACTIVE_CK CHECK(USER_ACTIVE IN('Y','N')),
	CONSTRAINTS USER_ID_UQ UNIQUE(USER_ID),
	CONSTRAINTS USER_NICKNAME_UQ UNIQUE(USER_NICKNAME),
	CONSTRAINTS SNS_TYPE_CK CHECK(SNS_TYPE IN('G','N','K')),
	CONSTRAINTS SNS_ID_UQ UNIQUE(SNS_ID)
);

INSERT INTO USER_INFO VALUES
(USER_INFO_SEQ.NEXTVAL, 'tydee.adm@gmail.com', 'messy071520', 'ADMIN', '관리자', SYSDATE, NULL, NULL, 'Y');

INSERT INTO USER_INFO 
VALUES(USER_INFO_SEQ.NEXTVAL, 'test@tydee.com', 'tydee1234', 'USER', 'test', SYSDATE, NULL, NULL, 'Y');

INSERT INTO USER_INFO 
VALUES (USER_INFO_SEQ.NEXTVAL, 'ham@naver.com', '1234', 'USER', '🍰', SYSDATE, NULL, NULL, 'Y');

SELECT USER_NO, USER_ID, USER_PW, USER_ROLE, USER_NICKNAME, USER_REGDATE, SNS_TYPE, SNS_ID, USER_ACTIVE
FROM USER_INFO;

DROP SEQUENCE MYTYDEE_SEQ;
DROP TABLE MYTYDEE;
CREATE SEQUENCE MYTYDEE_SEQ;
CREATE TABLE MYTYDEE(
	TINY_NO NUMBER PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	TINY_TYPE VARCHAR2(50) NOT NULL,
	TINY_TITLE VARCHAR2(500) NOT NULL,
	TINY_DEPTH NUMBER NOT NULL,
	TINY_CONTENT VARCHAR2(4000),
	TINY_IMAGE VARCHAR2(1000),
	TINY_REGDATE DATE NOT NULL,
	CONSTRAINTS MYTYDEE_UN_FK FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO),
	CONSTRAINTS TINY_TYPE_CK CHECK(TINY_TYPE IN('D','N'))
);

SELECT * FROM MYTYDEE;
