DROP SEQUENCE USER_INFO_SEQ;
DROP TABLE USER_INFO;
CREATE SEQUENCE USER_INFO_SEQ;
--유저 정보 테이블---
CREATE TABLE USER_INFO(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(500) NOT NULL,
	USER_PW VARCHAR2(1000) NOT NULL,
	USER_ROLE VARCHAR2(100) NOT NULL,
	USER_NICKNAME VARCHAR2(500) NOT NULL,
	USER_REGDATE DATE NOT NULL,
	SNS_TYPE VARCHAR2(20),
	SNS_ID VARCHAR2(500),
	USER_ACTIVE VARCHAR2(20) NOT NULL,
	CONSTRAINTS USER_ACTIVE_CK CHECK(USER_ACTIVE IN('Y','N')),
	CONSTRAINTS USER_ID_UQ UNIQUE(USER_ID),
	CONSTRAINTS USER_NICKNAME_UQ UNIQUE(USER_NICKNAME),
	CONSTRAINTS SNS_TYPE_CK CHECK(SNS_TYPE IN('G','N','K')),
	CONSTRAINTS SNS_ID_UQ UNIQUE(SNS_ID)
);

INSERT INTO USER_INFO 
VALUES(USER_INFO_SEQ.NEXTVAL, 'test@tydee.com', 'tydee1234', 'USER', 'test', SYSDATE, NULL, NULL, NULL, 'Y');


SELECT *
FROM USER_INFO

--------------------------------------------------------------
--------------------------------------------------------------


DROP SEQUENCE BOARD_SEC_SEQ;
DROP TABLE BOARD_SEC;
CREATE SEQUENCE BOARD_SEC_SEQ;
-- 중고거래 게시판 테이블 -- 
CREATE TABLE BOARD_SEC(

	SEC_NO NUMBER PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	SEC_TITLE VARCHAR2(500) NOT NULL,
	SEC_CONTENT VARCHAR2(4000) NOT NULL,
	SEC_PRICE NUMBER NOT NULL,
	SEC_IMAGE VARCHAR2(1000),
	SEC_REGDATE DATE NOT NULL,
	SEC_DELETE VARCHAR2(20) NOT NULL,
	CONSTRAINTS SEC_DELETE_CK CHECK(SEC_DELETE IN('Y','N')),
	CONSTRAINTS BOARD_SEC_UN_FK FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO)
);




SELECT *
FROM BOARD_SEC;

INSERT INTO BOARD_SEC
VALUES(BOARD_SEC_SEQ.NEXTVAL,1,'에어팟 프로','5월 초에 구매한 제품입니다.','150000',NULL,SYSDATE,'Y');

DELETE FROM BOARD_SEC
WHERE USER_NO =1;

SELECT SEC_NO, USER_NO, SEC_TITLE, SEC_CONTENT, SEC_PRICE, SEC_IMAGE, SEC_REGDATE, SEC_DELETE
FROM BOARD_SEC
JOIN USER_INFO USING (USER_NO);



------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------

DROP SEQUENCE SEC_COMMENT_SEQ;
DROP TABLE SEC_COMMENT;

-- 중고 거래 게시판 내의 댓글 관련 테이블 -- 
CREATE SEQUENCE SEC_COMMENT_SEQ;
CREATE TABLE SEC_COMMENT(
	SEC_COMM_NO NUMBER PRIMARY KEY,
	SEC_NO NUMBER NOT NULL,
	USER_NO NUMBER NOT NULL,
	SEC_COMM_CONTENT VARCHAR2(1000) NOT NULL,
	SEC_COMM_REGDATE DATE NOT NULL,
	SEC_COMM_DELETE VARCHAR2(20) NOT NULL,
	CONSTRAINTS SEC_COMM_DELETE_CK CHECK(SEC_COMM_DELETE IN('Y','N')),
	CONSTRAINTS SEC_COMMENT_SN_FK FOREIGN KEY(SEC_NO) REFERENCES BOARD_SEC(SEC_NO),
	CONSTRAINTS SEC_COMMENT_UN_FK FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO)
);

SELECT SEC_COMM_NO , SEC_NO, USER_NO, SEC_COMM_CONTENT, SEC_COMM_REGDATE,
	   SEC_COMM_DELETE,USER_ID
	   FROM SEC_COMMENT
	   
SELECT S.SEC_COMM_NO, B.SEC_NO, U.USER_NO, SEC_COMM_CONTENT, SEC_COMM_REGDATE, SEC_COMM_DELETE
FROM SEC_COMMENT S
JOIN BOARD_SEC B
ON S.SEC_NO = B.SEC_NO
JOIN USER_INFO U
ON U.USER_NO = S.USER_NO


INSERT INTO SEC_COMMENT
VALUES(SEC_COMMENT_SEQ.NEXTVAL, 1, 1 ,'쿨거래 감사합니다',SYSDATE, 'N','test@tydee.com')



































