SELECT * from BOARD_TIPS;

CREATE TABLE TIP_COMMENT(
	TIP_COMM_NO NUMBER PRIMARY KEY,
	TIP_NO NUMBER NOT NULL,
	USER_NO NUMBER NOT NULL,
	TIP_COMM_CONTENT VARCHAR2(1000) NOT NULL,
	TIP_COMM_REGDATE DATE NOT NULL,
	TIP_COMM_DELETE VARCHAR2(20) NOT NULL,
	CONSTRAINTS TIP_COMM_DELETE_CK CHECK(TIP_COMM_DELETE IN('Y','N')),
	CONSTRAINTS TIP_COMMENT_TN_FK FOREIGN KEY(TIP_NO) REFERENCES BOARD_TIPS(TIP_NO),
	CONSTRAINTS TIP_COMMENT_UN_FK FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO)
);


SELECT *
FROM TIP_COMMENT

SELECT *
FROM USER_INFO

INSERT INTO USER_INFO 
VALUES(USER_INFO_SEQ.NEXTVAL, 'test@tydee.com', 'tydee1234', 'USER', 'test', SYSDATE, NULL, NULL, NULL, 'Y');
/
